-------------------- PRIMERA CONSULTA ----------------------
/*
Histórico de los platos vendidos que han existido. Es decir que tiene que aparecer el año,
el nombre del plato, la cantidad de veces que se vendió (DE MAYOR A MENOR) y el dinero que reflejó esa venta */

SELECT 
	EXTRACT(YEAR FROM F.FECHA_FACTURA)AS FECHA, 
	PL.NOMB_PLATO, 
	SUM(DF.CANTIDAD_DETALLE),
	SUM(DF.VALOR_NETO) AS TOTAL
FROM FACTURA F
	INNER JOIN DETALLE_FACTURA DF ON F.ID_FACTURA = DF.ID_FACTURA
	INNER JOIN PLATO PL ON DF.ID_PLATO = PL.ID_PLATO
WHERE F.ID_FACTURA = DF.ID_FACTURA 
AND F.FECHA_FACTURA BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY 
	EXTRACT(YEAR FROM F.FECHA_FACTURA), 
	PL.NOMB_PLATO
ORDER BY SUM(DF.CANTIDAD_DETALLE) DESC



-------------------- SEGUNDA CONSULTA -----------------------
/*
Histórico de reservaciones (Cliente, cuantas reservaciones ha hecho, -cuantas reservaciones fueron canceladas-. 
Y cuanto dinero nos ha dejado cada cliente)
*/

SELECT
	EXTRACT(YEAR FROM RESERVACION.FECHA_RESERVACION) AS FECHA,
	(CLIENTE.NOMB_CLIENTE || ' ' || CLIENTE.APELL_CLIENTE) AS NOMBRES,
	(SELECT COUNT(ID_RESERVACION) FROM RESERVACION
	WHERE CLIENTE.ID_CLIENTE = RESERVACION.ID_CLIENTE ) AS RESERVACIONES,
	(SELECT COUNT(ID_RESERVACION) FROM RESERVACION
	WHERE CLIENTE.ID_CLIENTE = RESERVACION.ID_CLIENTE 
		AND RESERVACION.ESTADO_RESERVACION = 'CANCELADA') AS CANCELADAS,
	FACTURA.TOTAL_FACTURA AS TOTAL
FROM CLIENTE	
	INNER JOIN RESERVACION ON CLIENTE.ID_CLIENTE = RESERVACION.ID_CLIENTE
	INNER JOIN FACTURA ON CLIENTE.ID_CLIENTE = FACTURA.ID_CLIENTE
WHERE FACTURA.FECHA_FACTURA = RESERVACION.FECHA_RESERVACION
GROUP BY
	FACTURA.TOTAL_FACTURA, RESERVACION.FECHA_RESERVACION,
	CLIENTE.NOMB_CLIENTE, CLIENTE.APELL_CLIENTE,
	CLIENTE.ID_CLIENTE, RESERVACION.ID_CLIENTE

--------------------- TERCERA CONSULTA --------------------
/*
Por año que salga la cantidad de ingredientes que más se han gastado (ejemplo, en 2021 en carne se fueron 500 libras. 
En arroz se fueron 50 quintales de arroz) */

SELECT 
	EXTRACT(YEAR FROM F.FECHA_FACTURA) AS FECHA,
	I.NOMB_INGREDIENTE AS NOMBRE_INGREDIENTE,
	SUM(I.CANT_INGREDIENTE) AS CANTIDAD,
	M.DESCRP_MEDIDA AS DESCRIPCION
FROM RECETA R
	INNER JOIN INGREDIENTE I ON I.ID_INGREDIENTE = R.ID_INGREDIENTE
	INNER JOIN MEDIDA M ON I.ID_MEDIDA = M.ID_MEDIDA
	INNER JOIN PLATO P ON R.ID_PLATO = P.ID_PLATO
	INNER JOIN DETALLE_FACTURA DF ON DF.ID_PLATO = P.ID_PLATO
	INNER JOIN FACTURA F ON DF.ID_FACTURA = F.ID_FACTURA
WHERE I.ID_MEDIDA = M.ID_MEDIDA
AND F.FECHA_FACTURA BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY 
	EXTRACT(YEAR FROM F.FECHA_FACTURA),
	I.NOMB_INGREDIENTE, 
	I.CANT_INGREDIENTE,
	M.DESCRP_MEDIDA
ORDER BY SUM(I.CANT_INGREDIENTE) DESC
	

/* 
------------- Cuarta Consulta -------------
Histórico de atenciones de los meseros, es decir cuantas reservaciones ha atendido cada mesero 
(Yo he atendido 500 reservaciones y el numero de clientes) 
*/


SELECT 
	EXTRACT(YEAR FROM R.FECHA_RESERVACION) AS FECHA,
	(M.NOMB_MESERO || ' ' || M.APELL_MESERO) AS NOMBRES,
	COUNT(R.ID_MESA) AS NO_RESERVACIONES,
	COUNT(R.ID_CLIENTE) AS NO_CLIENTES
FROM CLIENTE C
	INNER JOIN RESERVACION R ON C.ID_CLIENTE = R.ID_CLIENTE
	INNER JOIN MESA ME ON R.ID_MESA = ME.ID_MESA
	INNER JOIN MESERO M ON ME.ID_MESERO = M.ID_MESERO
WHERE ME.ID_MESERO = M.ID_MESERO
GROUP BY
	EXTRACT(YEAR FROM R.FECHA_RESERVACION),
	M.NOMB_MESERO,
	M.APELL_MESERO;

