------------------ PROCEDIMIENTO ALMACENADO ------------------
/*
Un procedimiento almacenado que sea capaz de mandar el nombre de un chef y aparezca:
El nombre del mesero que haya atendido, el año y el número de clientes 
(que ordenaron el plato de ese chef)
*/

CREATE OR REPLACE FUNCTION CANT_CLIENTE(VARCHAR) RETURNS SETOF "record"
AS
$BODY$
	SELECT 
		(MESERO.NOMB_MESERO || ' ' || MESERO.APELL_MESERO) AS NOMBRES,
		EXTRACT(YEAR FROM FACTURA.FECHA_FACTURA) AS FECHA,
		COUNT(R.ID_CLIENTE) AS NO_CLIENTES
	FROM CLIENTE 
		INNER JOIN RESERVACION R ON CLIENTE.ID_CLIENTE = R.ID_CLIENTE
		INNER JOIN FACTURA ON CLIENTE.ID_CLIENTE = FACTURA.ID_CLIENTE
		INNER JOIN MESA  ON R.ID_MESA = MESA.ID_MESA
		INNER JOIN MESERO ON MESA.ID_MESERO = MESERO.ID_MESERO
		INNER JOIN DETALLE_FACTURA DF ON DF.ID_FACTURA = FACTURA.ID_FACTURA
		INNER JOIN PLATO ON DF.ID_PLATO = PLATO.ID_PLATO
		INNER JOIN RECETA ON PLATO.ID_PLATO = RECETA.ID_PLATO
		INNER JOIN CHEF ON RECETA.ID_CHEF = CHEF.ID_CHEF
		WHERE CHEF.NOMB_CHEF = $1
	GROUP BY EXTRACT(YEAR FROM FACTURA.FECHA_FACTURA),
		MESERO.NOMB_MESERO, MESERO.APELL_MESERO
$BODY$
LANGUAGE SQL;

SELECT * FROM CANT_CLIENTE('Daniel')
AS ("nomb_mesero" text, "fecha" double precision, "n_cliente" bigint)

------------------- CONSULTA IREPORT ------------------- 
/* Que se muestre en un diagrama de barras los platos vendidos de mayor a menor. */

SELECT 
	EXTRACT(YEAR FROM F.FECHA_FACTURA)AS FECHA, 
	PL.NOMB_PLATO, 
	SUM(DF.CANTIDAD_DETALLE)
FROM FACTURA F
	INNER JOIN DETALLE_FACTURA DF ON F.ID_FACTURA = DF.ID_FACTURA
	INNER JOIN PLATO PL ON DF.ID_PLATO = PL.ID_PLATO
WHERE F.ID_FACTURA = DF.ID_FACTURA 
AND F.FECHA_FACTURA BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY 
	EXTRACT(YEAR FROM F.FECHA_FACTURA), 
	PL.NOMB_PLATO
ORDER BY SUM(DF.CANTIDAD_DETALLE) DESC